### ISSUE TITLE
Issue with May 2019 data

### ISSUE THREAD

**Issue by billpine** [LCRoysterproject/transect#33]
Hi, the May 2019 data has issues (see "packet" file) with reconciliation with the obs column and the date column. See error messages in the data check tab. Also need to investigate why the drop down menus are not working once the file is posted from Steve's computer?   The links between data tabs are not persisting which I've not observed as a problem before.  It seems to want to reference a file that is sourced from Steve?  Has anyone seen this error when pulling from the data entry files I've posted?

**Comment by sbeck1** [comment]
These errors were fixed prior to next round of data entry, which will be pushed soon.  I'm not sure why the links are not persisting.  I would guess using multiple computers with differing version of excel could be the issue.  As we've had to add values to the pick lists, we occasionally encounter a message something like "bp must authorize this change", but then it lets us modify pick lists anyways.

**Comment by billpine** [comment]
Hi, Thanks for working on this.  Please test between computers then if you think that is the issue. With the entry I've done I've worked across computers and versions of Excel without issue.  How I test things is to push to my branch, then download and test and look at everything again (including the check tab).  I then do the pull request to the project page.

**Comment by billpine** [comment]
And yes there are no user controls on modifying the pick lists. It just throws those flags when there are values that exceed the specified ranges.
